name: Feature Request
description: Suggest a new feature or enhancement for Magic Resume
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Motivation
      description: What problem does this feature solve? Why is it needed?
      placeholder: |
        - What problem does this solve?
        - Who would benefit from this feature?
        - What is the use case?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: Describe any alternatives you've considered...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / Examples
      description: If applicable, add mockups, wireframes, or examples of similar features.
      placeholder: Drag and drop images here or paste URLs

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my workflow
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, examples, or information about the feature request.
      placeholder: Any other information that might be helpful...

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have provided a clear use case and motivation
          required: true
        - label: I have considered alternatives
          required: true

